export const SEQ_DRAFT = 0;
export const SEQ_REJECT = -1;

export const STATUS_APPROVED = 'Approved';
export const STATUS_REWORK = 'Rework';
export const STATUS_REJECTED = 'Rejected';

export const NOTES = [
    "NOTE: PLEASE PROVIDE COA/COI/LOG WITH MICROBIOLOGY & PHYSICO-CHEM ANALYSIS IN EVERY DELIVERY.  FOR MEAT PRODUCTS, PLEASE ALSO PROVIDE MEAT INSPECTION CERTIFICATE. *** PLEASE PROVIDE COPY OF PO REFERENCE/S DURING DELIVERIES", 
    "*** PLEASE PROVIDE COPY OF PO REFERENCE/S DURING DELIVERIES. FOR SERVICES, PLEASE PROVIDE SERVICE REPORT AFTER THE SERVICE."];

export const DELIVERY_ADDRESS = ['BLOCK 6 LOT 8, PSD II, DIVERSION ROAD, BUHANGIN, DAVAO CITY', 
    'DOOR 2 PLUG HOLDING BLDG, DIHO ROAD CABANTIAN, DAVAO CITY', 
    '#76 ANACONDA COMPOUND F. MARIANO AVE., DELA PAZ, PASIG CITY'];


// #76 ANACONDA COMPOUND F. MARIANO AVE., DELA PAZ, PASIG CITY
// BLOCK 6 LOT 8, PSD II, DOVERSION ROAD, BUHANGIN, DAVAO CITY
// DOOR 2 PLUG HOLDING BLDG, DIHO ROAD, CABANTIAN, DAVAO CITY
